[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[functions.stripe-webhook]
  included_files = ["netlify/functions/stripe-webhook.mjs"]